image: node:latest

cache:
  paths:
    - node_modules/

variables:
  webapp1: "WebApplication1"

stages:
  - build
 # - test
  - buildImage
  - pushImage

build:
  stage: build
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build
   
#test:
#  stage: test
#  script:
#  - npm run lint
#  - ./node_modules/@angular/cli/bin/ng test --single-run=true --browsers PhantomJS --watch=false

buildImage:
   stage: buildImage
   script:
      - docker build . -t unlegendnl/plantrfrontend

pushImage:
   stage: pushImage
   script:
     - "docker login --username unlegendnl --password 66fafb59-d9c4-4f7a-bf4c-96ef87c5d619"
     - "docker push unlegendnl/plantrfrontend"